---

- name: add apt key
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present
  when: ansible_os_family == 'Debian'

- name: add apt key
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox.asc"
    state: present
  when: ansible_os_family == 'Debian'    

- name: download apt repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ liberação_de_distribuição_ansible }} contrib"
    state: present
    update_cache: yes  
  when: ansible_os_family == 'Debian'

- name: Installing standard packages apt
  package:
    name: "virtualbox-{{ virtualbox_version }}"
    state: latest

- name: Register installed version
  shell: "echo $(virtualbox --help | head -n 1 | awk '{print $NF}')"
  register: virtualbox_version

- name: Getting Virtualbox Extension Pak
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{ virtualbox_version.stdout }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout }}.vbox-extpack"
    dest: "/tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout }}.vbox-extpack"
    force: True
    owner: 'root'
    group: 'root'
    mode: '0644'
  ignore_errors: True